name: hris

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: app_postgres
    environment:
      # PostgreSQL configuration
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # Persist database data in a named volume
      - postgres_data:/var/lib/postgresql/data
      # Initialize database with custom script
      - ./db:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  nginx:
    build:
        context: ./frontend
        dockerfile: Dockerfile.nginx
    container_name: app_proxy
    ports:
      - "80:80" 
      # - "443:443"  # Add this when you set up SSL
    volumes:
      # Map your local config file into the container
      - ./nginx/hris.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped


  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    environment:
      # Database connection string
      # Format: postgresql://user:password@host:port/database
      - ENV=production
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    expose:
      - "8000"  # Expose to internal network only
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/test-db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s # Give the DB time to wake up first
    restart: unless-stopped

# Named volume for PostgreSQL data persistence
volumes:
  postgres_data:

# Custom network for service communication
networks:
  app_network:
    driver: bridge